# static routes
# static routes is not enable to hot reload
- type: route
  target: hk
  values:
    # static routes for telegram
    # tg app use ip directly
    # https://core.telegram.org/resources/cidr.txt
    - 91.108.56.0/22
    - 91.108.4.0/22
    - 91.108.8.0/22
    - 91.108.16.0/22
    - 91.108.12.0/22
    - 149.154.160.0/20
    - 91.105.192.0/23
    - 91.108.20.0/22
    - 185.76.151.0/24

# domain pattern base glob
- type: domain
  target: hk
  values:
    - "*google*"
    - "*facebook.com"

# domain exclude pattern base glob
- type: excludeDomain
  values:
    - "www.googletagmanager.com"

# upstream CIDR match
- type: dnsCidr
  target: hk
  values:
    - 39.156.69.79/32
    - 220.181.38.148/32

# upstream IP GEO
# base https://dev.maxmind.com/geoip/geoip2/geolite2
# https://github.com/P3TERX/GeoLite.mmdb
# TODO support
- type: dnsGeoIp
  target: hk
  values:
    - hk
    - us
